import Image from 'next/image';
import Link from 'next/link';

export default function RefundPage() {
  return (
    <div className="min-h-screen px-6 py-24">
      <div className="mx-auto max-w-3xl">
        <Link href="/" className="inline-block mb-8">
          <Image src="/logo.svg" alt="Valor" width={80} height={20} className="h-5 w-auto" priority />
        </Link>
        <h1 className="text-3xl font-bold tracking-tight mt-8 mb-2">Refund Policy</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: June 7, 2026</p>

        <section className="space-y-6 text-muted-foreground leading-relaxed">
          <div>
            <h2 className="text-xl font-semibold text-foreground mb-2">1. Subscription Refunds</h2>
            <p>All subscription plans (Starter, Pro, Business) are billed monthly through Paddle. Because Valor provides immediate access to the full platform upon payment, <strong className="text-foreground">subscription fees are non-refundable</strong> except in the following cases:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>The Service is unavailable for more than 48 consecutive hours due to an issue on our end</li>
              <li>You were charged in error (e.g., duplicate charge)</li>
              <li>You cancel within 24 hours of your initial subscription purchase</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-foreground mb-2">2. Cryptocurrency Transactions</h2>
            <p>USDC tips and withdrawals processed through the Service involve blockchain transactions that are <strong className="text-foreground">irreversible once confirmed</strong> on the Base network. We cannot reverse, refund, or cancel confirmed blockchain transactions. Please double-check all wallet addresses and amounts before submitting withdrawals.</p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-foreground mb-2">3. Treasury Funds</h2>
            <p>USDC deposited into a community treasury wallet is held at the wallet address generated by the Coinbase CDP. Valor does not have access to or custody of these funds — they are controlled by the CDP-secured wallet. We cannot refund funds sent to incorrect addresses or networks.</p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-foreground mb-2">4. How to Request a Refund</h2>
            <p>To request a subscription refund, contact us at <a href="mailto:hello@valorapp.com" className="text-primary underline-offset-2 hover:underline">hello@valorapp.com</a> within the applicable period. Include:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>The email address used for your account</li>
              <li>The Paddle transaction ID (found in your receipt email)</li>
              <li>The reason for your request</li>
            </ul>
            <p className="mt-2">We will process valid refund requests within 10 business days.</p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-foreground mb-2">5. Chargebacks</h2>
            <p>If you dispute a charge through your payment provider, your account may be suspended until the dispute is resolved. We will provide all transaction records to your payment provider as requested.</p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-foreground mb-2">6. Contact</h2>
            <p>Refund inquiries: <a href="mailto:hello@valorapp.com" className="text-primary underline-offset-2 hover:underline">hello@valorapp.com</a></p>
          </div>
        </section>
      </div>
    </div>
  );
}
